export const EXPIRY_AFTER_APPROVAL_DAYS = 365;
export const ENABLE_RENEW_BEFORE_EXPIRY_DAYS = 30;
export const ENABLE_RENEW_AFTER_EXPIRY_DAYS = 365;
export const RENEW_GRACE_PERIOD_AFTER_EXPIRY_DAYS = 30;
